using System;
using System.IO;
using System.Text;

namespace DefenderRemover.Logic
{
    /// <summary>
    /// Generates PowerShell export for scripted disable.
    /// Covers: disable windows defender windows 11 permanently powershell,
    /// disable tamper protection windows 11 powershell.
    /// </summary>
    public static class PowerShellExporter
    {
        public static string GenerateDisableScript(bool includePolicy = true, bool includeServices = true)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Windows Defender Disabler — PowerShell Export");
            sb.AppendLine("# Generated by Windows Defender Disabler v14");
            sb.AppendLine("# Run as Administrator");
            sb.AppendLine();
            sb.AppendLine("# Disable Real-Time Protection");
            sb.AppendLine("Set-MpPreference -DisableRealtimeMonitoring $true");
            if (includePolicy) {
                sb.AppendLine();
                sb.AppendLine("# Disable Windows Defender Windows 11 permanently via policy");
                sb.AppendLine("$path = 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender'");
                sb.AppendLine("if (-not (Test-Path $path)) { New-Item -Path $path -Force }");
                sb.AppendLine("Set-ItemProperty -Path $path -Name DisableAntiSpyware -Value 1 -Type DWord");
            }
            if (includeServices) {
                sb.AppendLine();
                sb.AppendLine("# Disable Defender services");
                sb.AppendLine("Stop-Service WinDefend -Force -ErrorAction SilentlyContinue");
                sb.AppendLine("Set-Service WinDefend -StartupType Disabled -ErrorAction SilentlyContinue");
            }
            return sb.ToString();
        }

        public static void SaveScript(string path, bool includePolicy = true, bool includeServices = true)
        {
            var script = GenerateDisableScript(includePolicy, includeServices);
            File.WriteAllText(path, script, Encoding.UTF8);
        }
    }
}